"""
Distinct Powers
"""


def power(base, exponent):
    """func to calculate the power"""
    result = 1
    for _ in range(exponent):
        result *= base
    return result


def solver(n):
    """takes a single argument limit,
    which represents the upper limit for both a and b"""
    distinct_terms = set()

    for a in range(2, n + 1):
        for b in range(2, n + 1):
            distinct_terms.add(power(a, b))

    result = len(distinct_terms)
    return result


def answer():
    """How many distinct terms are in the sequence generated by a^b
    for 2<=a<=100 and 2<=b<=100"""

    return solver(100)


if __name__ == "__main__":
    print(answer())
    print(solver(5))
